n = input('Insira algo: ')
print('O tipo primitivo desse valor é:', type(n))
print('Ele é Numérico? ', n.isnumeric())
print('Ele é Alfabético? ', n.isalpha())
print('Ele é Alfanumérico? ', n.isalnum())
print('Ele está em maiúsculo? ', n.isupper())
print('Ele está em minúsculo? ', n.islower())
print('Está capitalizado? ', n.istitle())
